import Providers from './components/ui/Providers'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className="h-screen w-screen bg-slate-200 "lang="en">
      <body className='h-screen w-screen bg-slate-200 '>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
